### ISSUE TITLE
Add code coverage check to CI pipeline

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#126]
Research what the appropriate code coverage tool should be for our needs, then implement it into our Github actions pull request workflow. 

Let's start at 75% code coverage for now and adjust as we move forward into real feature implementation.

Exclude our `/prototype` pages from the coverage. 

### Acceptance criteria

- [x] code coverage tool is added to the repo
- [x] code coverage check is incorporated into pull request workflow
- [x] code coverage failures prevent pull request merges

**Comment by echappen** [comment]
Check out Code Climate, or any preferred way of doing this at Cloud.gov

**Comment by jduss4** [comment]
Looks like pages is using [istanbul](https://istanbul.js.org/) (as indicated by `nyc` before test commands).  We are already using jest for tests, and jest ships with code coverage tools, one of which is Istanbul if we would like to stick with that.
