### ISSUE TITLE
Consider use of src directory for app

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#212]
For ease of compliance, we would like to consider using a src directory structure for the app in order to separate app code from supporting code. 

Research pros/cons of structuring app this way.

reference:
https://nextjs.org/docs/app/building-your-application/routing/colocation
https://nextjs.org/docs/app/building-your-application/configuring/src-directory

### Acceptance criteria
- [ ] decision is documented on using src directory

**Comment by echappen** [comment]
If we encounter CI/Concourse issues with this while folks are out, put it in Blocked.

**Comment by jduss4** [comment]
Things we will want to make sure we can still do after moving the application itself to src:

CI / CD
- [ ] concourse pipeline can run tests and deploy app
- [ ] github actions can run tests / build app

Locally
- [ ] can run tests, build, etc
- [ ] typescript import paths function normally
- [ ] scripts like the token-refresh work on app restart
- [ ] can still manually deploy the app to cloud.gov
- [ ] assets load appropriately
