### ISSUE TITLE
1Aiii. view all users > view select assigned spaces and roles

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#219]
In list view

### Steps to delivery (an iterations definition of done)
- [ ] design & define component for viewing org roles assign to users
- [ ] feasibility review/co-work
- [ ] product review: place in ready for build, prioritize if needed
- [ ] build
- [ ] user testing

### Acceptance criteria

**Comment by hursey013** [comment]
This has been implemented and reworked.
