### ISSUE TITLE
Eliminate having two vertical scrollbars/scroll areas in content section of page templates

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#253]
Would like to eliminate having two vertical scrollbars/scroll areas. One in the browser window and one in the user list. See gif:
![2024-06-03_15-35-39 (1)](https://github.com/cloud-gov/cg-ui/assets/93934808/3844712a-a5b1-4055-9e61-8a36d50ee304)

---
**For desired scroll:** Nav content would be sticky and org header would also be sticky. 
We want them to always have the Org (app section) in context as all content and edit flow are in relation to org. i.e. removing/adding user to an org. 
Here are gifs of desired state:
![2024-06-03_15-17-37 (1)](https://github.com/cloud-gov/cg-ui/assets/93934808/bacc3162-6913-451d-9c37-5b9f2c84be44)

Ex. **with notifications**: in context despite where the user is. I.e. after confirming a modal action.
![2024-06-03_15-23-18 (1)](https://github.com/cloud-gov/cg-ui/assets/93934808/9daaf751-f2ed-4b46-bdaf-3e8a64e08d4b)

**Last option**
If the above is too difficult this is a better option than current implementation: org header is not sticky and the browser window height grows with the content leaving just the browser scrollbar/area for vertical scroll. Why: In current implementation, it's not intuitive that there are two vertical scroll areas (for system types app scroll areas should be indicated and in a single view). This would require the footer to be sticky to bottom of the browser. We have determined that the footer takes up too much space and low in user need - so shouldn't be sticky.

![2024-06-03_15-24-32 (1)](https://github.com/cloud-gov/cg-ui/assets/93934808/582d6c41-bb61-477b-9a0a-13076b873687)

_Originally posted by @janelx in https://github.com/cloud-gov/cg-ui/issues/245#issuecomment-2146253173_

**Comment by echappen** [comment]
Closing due to outdated design
