### ISSUE TITLE
Decide on roles display strategy

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#268]
Decide on roles simplification proposal as described in the [roles research document](https://docs.google.com/document/d/1hoTtJs0rbeXWxPCCt0FE2QvMnhiUbl846jH53HNMWwA/edit?usp=sharing).

Decision blocks #210, #219, #221 

### Acceptance Criteria
- [ ] ADR on decision is accepted

**Comment by hursey013** [comment]
Closed with https://github.com/cloud-gov/cg-ui/pull/333
