### ISSUE TITLE
Ready Figma for user testing

### ISSUE THREAD

**Issue by janelx** [cloud-gov/cg-ui#272]
For "remove user", I think I need to update the prototype to include:
[Link to screens in WIP](https://www.figma.com/design/uU63HcBZQfAjx1OJuY0yti/Cloud.gov---Wireframes?node-id=879-25104&t=gD1FIcsSZcL1tGhq-1)

- [ ] Longer list of of users
- [ ] "Activate" remove button for multiple users scattered through out the list (just let me know who many)
- [ ] May want to test error state? We just need a practical error state from eng

Anything else? @lauraponce  just let me know whenever you have script.

- [ ] Try programming logic for edit orgs in Figma
[Link to screens in WIP](https://www.figma.com/design/uU63HcBZQfAjx1OJuY0yti/Cloud.gov---Wireframes?node-id=840-23095&t=gD1FIcsSZcL1tGhq-1)

**Comment by echappen** [comment]
Closing as outdated
