### ISSUE TITLE
Design principles: design review session

### ISSUE THREAD

**Issue by beepdotgov** [cloud-gov/cg-ui#356]
As outlined in #348, we're going to define a set of initial design principles for cloud.gov. Our first step in doing so is to conduct a review of the redesign's earlier design work, talking through its current design gaps, and discuss in more detail why something is or isn’t working.

This conversation should help us identify some of [cloud.gov](http://cloud.gov/)’s shared values around design, which will, in turn, be useful inputs for a subsequent mini-workshop session on defining design principles.

_Can this task be done in one increment?_

Yes.

### Acceptance Criteria
- [x] Conduct a lightly facilitated design review with @hursey013, @sknep, and @lauraponce.
- [ ] Document key concepts, phrases, and themes from the design review, which will be used as inputs for the subsequent design principles discussion.

**Comment by beepdotgov** [comment]
(Updated [prior comment](https://github.com/cloud-gov/cg-ui/issues/356#issuecomment-2236516550) with the correct document link: https://docs.google.com/document/d/1JiOcl9bW0EHsgBN1E5cLyyShG7FHnHllkVtK6Td-hg8/edit)

**Comment by hursey013** [comment]
@beepdotgov these themes are spot on, well done!

**Comment by beepdotgov** [comment]
Thanks @hursey013! So glad to hear it.

Got a thumbs-up from @sknep in Slack, so closing this out! Excited for round 2.
