### ISSUE TITLE
Design principles: mini-workshop

### ISSUE THREAD

**Issue by beepdotgov** [cloud-gov/cg-ui#357]
As outlined in #348, we're going to define a set of initial design principles for cloud.gov. To do so, we'll conduct a facilitated mini-workshop on cloud.gov's design principles, using three sets of inputs to help seed the discussion:

- The results from the earlier design review (#356),
- Key lessons from the recent user research findings, and
- [cloud.gov](http://cloud.gov/)’s own [customer service objectives](https://cloud.gov/docs/overview/customer-service-objectives/)

The output of this session would be a living document outlining the principles we’ve heard, which we could iterate on throughout the remainder of the engagement.

_Can this task be done in one increment?_

Yes, pending availability.

### Acceptance Criteria
- [x] Conduct a facilitated mini-workshop on design principles with the redesign team.
- [x] Document the initial set of design principles.
- [x] Submit the draft design principles document for @hursey013 and @sknep for review/feedback.

**Comment by beepdotgov** [comment]
Here are [the design principles](https://docs.google.com/document/d/1EVulI6xVxMTJ0z4E1QBZtI8uNRs_4OezfUBr0jqGat4/edit) that came out of yesterday’s workshop:

> For the new Cloud.gov Dashboard, our design will be:
> 
> 1. **Trustworthy.** We value our relationship with our users, and the trust they place in our platform. We earn that trust by making safe, unsurprising experiences, allowing our users to focus on their mission instead of ours.
> 2. **Clear and direct.** We favor clarity over cleverness. We make predictable interface choices, and clarify complex structures or concepts. Doing so allows our users to complete tasks quickly and easily.
> 3. **Proactive and helpful.** Our customers may be working in isolation, but Cloud.gov sees the patterns that emerge across hundreds of federal apps and websites. Our product puts these lessons in practice for our users.
> 4. **User-centered.** Our users build and maintain federal software across many different agencies, roles, and approaches. We meet our users where they are: by involving them in our research, by listening to them, and by adopting the language and patterns that are familiar to them.
> 5. **Part of a path to our future.** Cloud.gov supports our users today, and will continue to do so in the future. We create scalable, extensible interfaces that grow and adapt alongside our users’ needs, and with our own evolving product offerings.

I said this yesterday during the workshop, but I think this is an _incredibly_ strong set of design principles.

@sknep: since @hursey013’s OOO, how would you like to handle approval / closing out this issue?

**Comment by sknep** [comment]
Wonderful -- excited to see these in practice in the work and in our conversations. Thanks Ethan!
