### ISSUE TITLE
Find a programmatic way to distinguish service accounts from human accounts

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#363]
In [round 1 of our research](https://docs.google.com/document/d/1wmYLxD2SO_KkJjjq5jDRSOUyqU3matHTk4fY-v4n2Yo/edit#heading=h.7rjexo8wtke), we found that users wanted a way to filter org members by whether a member was a human being or a service account (i.e. an automated service, like Github or some other CI/CD broker; a robot). There's currently no programmatic way to distinguish service accounts, but we believe it's worth exploring how to do this. 

Research ways we could get this data and assess effort vs. impact of the implementation options. Options could involve appending to our current data source, or creating a new data source. The result should be an ADR that describes the context and limitations, implementation options, and proposal for the best option going forward. 

_Ensure this issue has a clear Definition of Done in the Acceptance Criteria list below:_ 
### Acceptance Criteria
- [ ] ADR is shared with the team for feedback

**Comment by jduss4** [comment]
For the sake of documenting a finding, I discovered that service account created users have a username / presentation name which is the same as the GUID for a service credential binding.
