### ISSUE TITLE
Create a non-UI service to search and filter org members

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#364]
From round 1 of user research, we found that [users would like a way to search and filter org members](https://docs.google.com/document/d/1wmYLxD2SO_KkJjjq5jDRSOUyqU3matHTk4fY-v4n2Yo/edit#heading=h.dje69cb7bznl). 

Possible sorting options include: alphabetical, account created date, last login, and login expiration. 

Possible filtering options include: spaces, roles, and expired logins.

Because UI is still being determined, build a backend service to search and filter by the above criteria. Build an initial input field on the users list page (`/orgs/[orgID]`) to make it functional, using OOTB USWDS components and styling. Build with re-use in mind: we'll likely need to search and filter any kind of list, like apps, spaces, services, etc. 

For text search: first do the search on a "search" action, then work your way up to dynamically-typed search if time permits. 

Sorting will be done in another issue. 

### Acceptance Criteria
- [ ] Org manager can search and filter the org members list with the above parameters, either with a "search" action or with dynamic typing
- [ ] Feature is functional, but not designed
- [ ] Feature follows [USWDS accessibility guidance](https://designsystem.digital.gov/components/search/) for search input

**Comment by echappen** [comment]
@beepdotgov Would a dynamic search bar be preferable over having a submit button? If not, I can remove it from the issue.

**Comment by beepdotgov** [comment]
@echappen Given all the complexity that comes with live/dynamic search, I like the way you've structured this: starting with the submit button feels right to me.

**Comment by echappen** [comment]
@beepdotgov Great, thanks for clarifying
