### ISSUE TITLE
Review the roles terminology to determine best course of action

### ISSUE THREAD

**Issue by lauraponce** [cloud-gov/cg-ui#366]
### Background context
In our first round of user research, we learned that the [naming conventions for roles is confusing for users](https://docs.google.com/document/d/1wmYLxD2SO_KkJjjq5jDRSOUyqU3matHTk4fY-v4n2Yo/edit#heading=h.q3oh7kaf530f), even the most experienced Cloud.gov users. In the discussion, we talked about some paths forward on this but there's no clear solution at the moment. This ticket is for figuring out the best course of action to reduce confusion around the role names. Here are some of the considerations that came out of the team's discussion:

- Reminding users what the roles/permissions entail in the context of when they're setting it up for a new user
- Would recommend involving security folks (William and Sean)
- Having a separation of roles and capabilities
- Renaming the roles to something self-explanatory 

### Acceptance Criteria
- [x] There is a decision for what to do about the role names
- [ ] A new GH ticket is entered for that work to be done (if there is any)

**Comment by echappen** [comment]
Done in [this ADR](https://github.com/cloud-gov/cg-ui/blob/main/docs/adr/008_roles-display-strategy.md)
