### ISSUE TITLE
Create draft diagrams for current application

### ISSUE THREAD

**Issue by jduss4** [cloud-gov/cg-ui#371]
In order to prepare for upcoming compliance work, we should consider what diagrams we may need (network, data flow, etc), what diagramming tool / utility to use, and begin to sketch them out for our application's current state.

This issue will involve consulting with the Cloud.gov compliance staff to understand what diagrams they will require and their preferred presentation.

### Acceptance Criteria
- [ ] Understand the types of diagrams that will be required
- [ ] Choose a diagramming tool, ADR is created if multiple options were weighed
- [ ] Rudimentary diagrams have been created (ideally as code and added to this repository)

**Comment by echappen** [comment]
Outcome from our first Diagram Jam: Brian will copy and alter the [Mermaid code](https://github.com/cloud-gov/cg-diagrams/blob/79377a3158f7db0a4293d8e0ad4be69331cd9117/source/diagrams/pages/web.mmd?short_path=6f3e05e) that generated the [CG Pages diagram](https://github.com/cloud-gov/cg-diagrams/blob/79377a3158f7db0a4293d8e0ad4be69331cd9117/out/diagrams/pages/web.png) to make our own diagram. It’s mostly a matter of removing nodes from pages diagram to get ours.

**Comment by echappen** [comment]
Closing in favor of #438
