### ISSUE TITLE
set screen width and center content

### ISSUE THREAD

**Issue by jduss4** [cloud-gov/cg-ui#414]
We need to cap the width of the display at 1200px / 75 rem and center everything in the window.

This came up during a conversation with @beepdotgov and I wanted to make an issue before it became lost to time.

### Acceptance Criteria
- [ ] Widescreen is capped at specified width, content is centered

**Comment by beepdotgov** [comment]
Thanks for logging this, @jduss4. (Updated [Figma with a comment/note](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz?node-id=312-8094#906815083) as well.)
