### ISSUE TITLE
Move CSS USWDS mixins into html as utility classes

### ISSUE THREAD

**Issue by jduss4** [cloud-gov/cg-ui#425]
In #419 , I chose to use mixins and functions in the Sass file for the global nav, but we have decided to switch back to using inline uswds utility classes where possible and keeping only those pieces of CSS that must be custom in the Sass file(s).

### Acceptance Criteria
- [x] As many utility classes as possible have been moved to HTML
- [x] Duplicative code has been abstracted out (for loops, components, etc)
- [ ] The overall design and functionality of the global nav remains the same as the current main branch

**Comment by echappen** [comment]
Discussion this thursday at engineering sync about overall design strategy, but otherwise Claire and Jess will meet on this PR and approve.
