### ISSUE TITLE
Plan round 3 of user research

### ISSUE THREAD

**Issue by lauraponce** [cloud-gov/cg-ui#430]
### Acceptance Criteria
- [x] [Research plan is created](https://docs.google.com/document/d/1pXj2vHFWxYDIKatBlzVAg-aR7yXjZzq9R1bIVp2mriM/edit#heading=h.x23pmmz9qr8b)
- [ ] Interview questions are drafted
- [ ] Team reviews research goals and interview questions and is aligned on the plan for round 3 of research

**Comment by hursey013** [comment]
Completed with https://docs.google.com/document/d/1zcT0TV1JLEz-jy5xrljWwzLdRh_O4tr8SC-q9mrM8JY/edit#heading=h.jmjn81mtfaop and https://docs.google.com/document/d/11LFfJOvh5DzqE1SSZWsTEQOl-BXfOAXn5JVukBH-8Zo/edit#heading=h.ux113m1or1v8
