### ISSUE TITLE
Create SCR Diagram Draft for Dashboard

### ISSUE THREAD

**Issue by chizo-gov** [cloud-gov/cg-ui#438]
### Acceptance Criteria

- [x] First pass of SCR Diagram is drafted
- [x] Diagram includes all data inputs/outputs

**Comment by echappen** [comment]
Outcome from our first Diagram Jam: Brian will copy and alter the [Mermaid code](https://github.com/cloud-gov/cg-diagrams/blob/79377a3158f7db0a4293d8e0ad4be69331cd9117/source/diagrams/pages/web.mmd?short_path=6f3e05e) that generated the [CG Pages diagram](https://github.com/cloud-gov/cg-diagrams/blob/79377a3158f7db0a4293d8e0ad4be69331cd9117/out/diagrams/pages/web.png) to make our own diagram. It’s mostly a matter of removing nodes from pages diagram to get ours.

**Comment by hursey013** [comment]
Closed with https://github.com/cloud-gov/cg-ui/pull/452
