### ISSUE TITLE
Design Dashboard authentication experience

### ISSUE THREAD

**Issue by beepdotgov** [cloud-gov/cg-ui#477]
Per increment planning, we’ve decided to refine our authentication workflow, and provide a better “welcome mat”-style experience for logged-out visitors.

We’ll define this further in design, but there are a few opportunities to improve over what we currently [have on the prototype’s logged-out state](https://cg-ui.dev.us-gov-west-1.aws-us-gov.cloud.gov/):

- Briefly explaining the purpose of the app
- Remove debugging information from the page
- Stretch goal: automatically direct logged-in users to the appropriate org page (if possible)

_Can this task be done in one increment?_

Yes.

### Acceptance Criteria
- [x] Designs are accepted by cloud.gov
- [ ] Designs have been reviewed for technical feasibility, and handed off for implementation

**Comment by beepdotgov** [comment]
@hursey013 Jotted down a few notes from increment planning RE: the authentication workflow. I’ll get to work on sketching out a few concepts, but I thought I’d check: does this feel like it adequately covers the scope of what’s needed for this sprint? Anything you’d update or add?

**Comment by beepdotgov** [comment]
@hursey013 @sknep, good morning! I’ve pulled together a few initial sketches for a pre-authentication page. A few things of note:

1. I’ve introduced a refined footer, which should line up a bit better with our layout and colors.
2. The content’s pulled directly from [cloud.gov’s current pre-authentication page](https://login.fr.cloud.gov/login).

Happy to discuss either/both of those items in more detail! Just wanted to note them before I dive in.

---

I’ve pulled together three basic layouts:

1. One treatment patterned off our current “default” page layout;
2. One treatment with a bit more of a “splash” layout;
4. Another with a more condensed “card” layout.

As usual, they’re all [available in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1036-11667&node-type=SECTION&t=WEIY5Kyg5LCrAWCD-0), and also attached below.

Here the three layout mockups in sequence:

<details>
<summary><strong>“Default” layout</strong></summary>

<img width="1266" alt="Welcome mat — standard" src="https://github.com/user-attachments/assets/94cd61fe-7bb4-401f-804c-b0d3afc15021">
</details>

<details>
<summary><strong>“Splash” layout</strong></summary>

<img width="1266" alt="Welcome mat — splash" src="https://github.com/user-attachments/assets/db25ff69-9638-4e7e-a4c7-d6d241e027ee">
</details>

<details>
<summary><strong>“Card” layout</strong></summary>

(I debated on the best logo to lead with here, so I’ve included three variations.)

<img width="1266" alt="Welcome mat — card" src="https://github.com/user-attachments/assets/4ef07dde-e166-4c94-b00b-d66575dadf2f">
<img width="1266" alt="Welcome mat — card (cloud gov, variant 1)" src="https://github.com/user-attachments/assets/439a711d-4b20-4e8a-9b68-2205fab3262b">
<img width="1266" alt="Welcome mat — card (cloud gov, variant 2)" src="https://github.com/user-attachments/assets/451f5f28-80a7-4521-868a-374843a9cddf">
</details>

Those are the three sketches!

---

Here’s what I’m wondering:

1. Do any of these directions feel more (or less!) appropriate for the pre-auth content?
2. Do we want to have the top-level navigation bar on this page?
3. How’s the footer feel to you two?

Let me know if you’d like to set up a time to review these in a call. And thanks for taking a look!

**Comment by beepdotgov** [comment]
Met with @hursey013 and @sknep, and got a bit more definition on the scope here — thanks, both! Jotting down my notes from the call.

Broadly, there are three threads involved in getting someone to our dashboard:

1. The pre-authentication experience — what users see _before_ they log in
2. The existing login/UAA flow from https://login.fr.cloud.gov/login — what users see _in order to_ log in
3. The “welcome mat” — what users see _after_ they log in

Here are my notes of what we discussed:

1. We’re comfortable _not_ designing a page for the pre-authentication experience (item 1 above). If an unauthenticated user comes to our dashboard, we can direct them to the login form.
  - This makes me think: we’ll have to decide where someone lands when they log out. Is that cloud.gov?
1. The login flow (item 2 above; what I started designing) is out of scope. Cloud.gov may likely use the above designs at some point to refine the flow, but it’s not worth tackling during the engagement with 18F.
2. The “welcome mat” will be limited for now, but will grow over time. Some ideas that came up:
  - For now, its main purpose is to direct users to other parts of the dashboard, so they can quickly achieve their tasks. Some cards that link to key parts of the app (e.g. user management, billing, app management, [other core tasks](https://gsa-tts.slack.com/archives/C065GC3R139/p1724968590565509)) should be the main focus.
  - Some wish list items we might want to include in the design (note: these elements wouldn’t necessarily be built/implemented by 18F):
    - There’s a product need to be able to show account-level messages to the end user (“Your IAA is expiring in 30 days”, “You have 20 unresolved security issues”, “10 user accounts are expiring in the next 30 days”). Having a message style of varying importance would be useful.
    - Eventually, documentation might be included somewhere in the app; a card that hints at that functionality would be useful.

Brian, Sarah, let me know if I missed anything.

**Comment by hursey013** [comment]
Thank you for capturing all of that @beepdotgov, looks spot on 🎯

**Comment by beepdotgov** [comment]
@hursey013 @sknep, thank you _very_ much for your time yesterday. Here’s a pass on our post-auth “welcome mat” page (also [available in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1083-19219&node-type=SECTION&t=WEIY5Kyg5LCrAWCD-0)):


<img width="1266" alt="Welcome mat — standard" src="https://github.com/user-attachments/assets/d5d97850-ce51-4cd1-8fb9-606bf91fc8d2">


As you’ll see, I’ve broken this up into three main sections:

- Some “traffic management” cards, where the user can navigate to the main sections of Dashboard. (The text for each is obviously FPO, but feedback is very welcome!)
- A “recent messages” block, where account-level messages could appear.
- A section to display links to (contextually relevant? popular?) documentation.

I’d love any feedback you might have on the design! I’m specifically curious about:

1. How does the design feel for the “traffic management” cards? Do we need more cards? (Or different cards entirely?)
2. I realize 18F likely won’t be building these modules, but: how do the “recent messages” and documentation sections line up with what you’d expect to see there?

Let me know what you think! And as always, happy to get on a call to discuss.

**Comment by beepdotgov** [comment]
@sknep @hursey013 Thanks for your time this morning! Here’s a revised version of the “welcome mat” (also [in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1138-29756&node-type=FRAME&t=VSDaf7l6m3et6DOz-0), as ever):

<details>
<summary><strong>Mockups:</strong></summary>
<h3>With icons:</h3>
<img width="1266" alt="Welcome mat — with icons" src="https://github.com/user-attachments/assets/61c72b23-1697-484c-b849-91f398a65975">

<h3>Text-only:</h3>
<img width="1266" alt="Welcome mat" src="https://github.com/user-attachments/assets/9531dea1-720e-4ab2-a3fd-c6c8c61da5bc">
</details>

Here’s what’s updated in this version:

- Swapped Applications and Billing in the up-front “traffic management” cards
- Added a few tiers of severity to the messages
- Pulled the highest-priority message up to the top of the page
- Added a categorization label to the ~documentation~ “resources” block, so Cloud.gov could optionally include other kinds of content (e.g., blog entries)
- Added a documentation search bar to the resources
- Moved the help/support CTA closer to the footer
- Added a status link to the footer

One item of note: when I added icons to the up-front cards, I felt like the page got a little _too_ icon-heavy; that’s why I’ve included a text-only version of the cards. This feels a little clearer to my eye, but I’d love to hear what you two think!

Once this feels solid to you both, I’ll get a small screen layout prepped, and talk with Eleni about next steps!

**Comment by sknep** [comment]
🙅 👥 🦾📊

**Comment by beepdotgov** [comment]
Hi folks! Synced with @sknep and @hursey013 this morning, and we’ve got final designs for the welcome mat! 🎉 Attached below, but also [in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1150-18743&node-type=section&t=gqzEqw3wlpCuDBlR-0). We’ve decided to keep the icons for implementation, and we’ll see how well they shake out with our users.

Two items of note:

- Up until now, the designs have included a bunch of features that don’t yet exist. (A card to manage applications; the resources section; alerts.) We’ve prepped a “now” design we’ll use for implementation, well, _now_, and the other features will be implemented by Cloud.gov at some later date.
- I’ve included small screen versions of both designs. (But again, we’ll just use the “now” design for implementation.)

@echappen, just a quick ping to say that this is ready for a feasibility review!

<details>
<summary><strong>Mockups:</strong></summary>

<h3>Welcome mat — “now” version</h3>
<h4>Widescreen</h4>
<img width="1266" alt="Welcome mat — v now" src="https://github.com/user-attachments/assets/46824c49-4714-439c-85c6-689d5f09ab5f">
<h4>Small screen</h4>
<img width="398" alt="Welcome mat — small screen" src="https://github.com/user-attachments/assets/346db1fc-148a-4979-bff6-d6959f006ea6">

<h3>Welcome mat — “later” version</h3>
<h4>Widescreen</h4>
<img width="1266" alt="Welcome mat — v next" src="https://github.com/user-attachments/assets/88b7d45d-a88d-4ed0-a91e-e04eccae57dc">
<h4>Small screen</h4>
<img width="398" alt="Welcome mat — small screen (v next)" src="https://github.com/user-attachments/assets/6a0a21f9-3775-4fe8-91ce-f26fde3b72a0">

</details>

**Comment by hursey013** [comment]
Quick note: for unauthenticated users accessing the dashboard or a nested link within the dashboard, we would like to redirect folks to the login flow: https://github.com/cloud-gov/cg-ui/issues/494. That work can be tracked separately, let's continue to use this issue for the _authenticated_ landing page experience.

**Comment by beepdotgov** [comment]
Thanks for calling that out, @hursey013! [Noted in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1150-18743&node-type=section&t=gqzEqw3wlpCuDBlR-0) as well.

**Comment by beepdotgov** [comment]
Closing this out, and moving over to #529! 🚀
