### ISSUE TITLE
Define all the ways we can quantify a Cloud.gov account

### ISSUE THREAD

**Issue by chizo-gov** [cloud-gov/cg-ui#499]
Longer term strategy questions: 
- What are the dimensions by which we describe a Cloud.gov account? 
- What data do we want to show to people? (Example: number of users, traffic) 
- What metrics do we use to track success?

This may be the outcome of details from the competitive analysis and design hierarchy research.

**Comment by hursey013** [comment]
Moving discussion to https://github.com/cloud-gov/cg-ui/issues/501

**Comment by chizo-gov** [comment]
[Captured in Future Research](https://docs.google.com/document/d/11LFfJOvh5DzqE1SSZWsTEQOl-BXfOAXn5JVukBH-8Zo/edit)

Also captured in ways to measure success in [Dashboard's mission model canvas](https://app.mural.co/t/gsa6/m/gsa6/1729259097291/09d57f87b992cc7730d8440f60b19d7677d5961e)
