### ISSUE TITLE
Create "welcome mat" for authenticated users

### ISSUE THREAD

**Issue by cannandev** [cloud-gov/cg-ui#529]
## Acceptance criteria

- [x] Cards: USWDS card component. Button links to users and billing, respectively. If they don't have access to one, don't show the card. 
  - If I don't have permission to card (users or billing), adjust other cards (expand or move over - judgement call). 
- [x] Users card: live update for number of users in currently picked organization (see #410).
  -  If I'm on org A and choose Org B from the picker, update the Dashboard with Org B info.
- [x] Blog: automatically pull in the latest entry from https://cloud.gov/news/ via feed
  - currently moving to 11ty 
- [ ] Footer: Updated version ❗ 
- [x] Mobile: adjusted sizing/spacing 

⚠️ Remember, there is no "logged out" welcome mat view.  

## Design notes
> Hi folks! Synced with @sknep and @hursey013 this morning, and we’ve got final designs for the welcome mat! 🎉 Attached below, but also [in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1150-18743&node-type=section&t=gqzEqw3wlpCuDBlR-0). We’ve decided to keep the icons for implementation, and we’ll see how well they shake out with our users.
> 
> 
> 
> Two items of note:
> 
> 
> 
> - Up until now, the designs have included a bunch of features that don’t yet exist. (A card to manage applications; the resources section; alerts.) We’ve prepped a “now” design we’ll use for implementation, well, _now_, and the other features will be implemented by Cloud.gov at some later date.
> 
> - I’ve included small screen versions of both designs. (But again, we’ll just use the “now” design for implementation.)
> 
> 
> 
> @echappen, just a quick ping to say that this is ready for a feasibility review!
> 
> 
> 
> <details>
> 
> <summary><strong>Mockups:</strong></summary>
> 
> 
> 
> <h3>Welcome mat — “now” version</h3>
> 
> <h4>Widescreen</h4>
> 
> <img width="1266" alt="Welcome mat — v now" src="https://github.com/user-attachments/assets/46824c49-4714-439c-85c6-689d5f09ab5f">
> 
> <h4>Small screen</h4>
> 
> <img width="398" alt="Welcome mat — small screen" src="https://github.com/user-attachments/assets/346db1fc-148a-4979-bff6-d6959f006ea6">
> 
> 
> 
> <h3>Welcome mat — “later” version</h3>
> 
> <h4>Widescreen</h4>
> 
> <img width="1266" alt="Welcome mat — v next" src="https://github.com/user-attachments/assets/88b7d45d-a88d-4ed0-a91e-e04eccae57dc">
> 
> <h4>Small screen</h4>
> 
> <img width="398" alt="Welcome mat — small screen (v next)" src="https://github.com/user-attachments/assets/6a0a21f9-3775-4fe8-91ce-f26fde3b72a0">
> 
> 
> 
> </details> 

 _Originally posted by @beepdotgov in [#477](https://github.com/cloud-gov/cg-ui/issues/477#issuecomment-2353386573)_

**Comment by echappen** [comment]
@hursey013 What url should the "access billing" link take you to? 

@beepdotgov Also, if this is a "now" design, should we adjust the help text for the Billing section to exclude what's further down the road? (viewing invoices, etc)

![Image](https://github.com/user-attachments/assets/74312b12-f24e-401e-898a-fa22489697a9)

**Comment by beepdotgov** [comment]
Thanks so much, @echappen — so glad you flagged this, that card could definitely use some adjustment. Depending on what @hursey013 decides for handling that link, I can definitely update the text to match.

**Comment by hursey013** [comment]
I know the idea of a `coming soon` card in the actual UI isn't ideal, but for now, what do you all think about adjusting this card to represent the usage metrics page with a deactivated button and activating it once it's implemented? Otherwise I think the only other option is likely just to drop that card entirely.

**Comment by beepdotgov** [comment]
Either option sounds great to me, though between the two I’d vote for dropping the card for now. It’s easy enough to restore once the usage page is properly live, and having the Users card span two columns could look nice in the interim.

(Some of this is coming from working on one too many products where a “coming soon” feature had to slip due to new priorities, so this could just be my biases talking 😅)

**Comment by hursey013** [comment]
I hear ya, let's drop it for now and stick with the `Users` card with whatever design treatment looks best to you.

**Comment by echappen** [comment]
Noting details from discussion:

1. For blog posts, There are currently two feeds the site generates, https://cloud.gov/updates.xml (blog) and https://cloud.gov/support.xml (knowledgebase)
2. Change manage users url to `/orgs/:org_id/users` 
3. Make welcome mat url `/orgs/:org_id`
4. In middleware, when user authenticates and visits root (`/`), redirect them to last viewed org (use org id from cookie). If none exists, send them to root and set the last viewed org id cookie as first org returned in /orgs CF API call.
